### ISSUE TITLE
Game crashes when steam locomotive reaches 100 degrees (TC 5.0.2 - 1.7.10)

### ISSUE THREAD

**Issue by mihaialexandru520168** [Mrbrutal/Traincraft-5#104]
--- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 4/1/21 8:07 PM
Description: Updating screen events

io.netty.channel.ChannelException: connection refused
	at io.netty.channel.local.LocalChannel$LocalUnsafe.connect(LocalChannel.java:361)
	at io.netty.channel.DefaultChannelPipeline$HeadHandler.connect(DefaultChannelPipeline.java:1008)
	at io.netty.channel.DefaultChannelHandlerContext.invokeConnect(DefaultChannelHandlerContext.java:494)
	at io.netty.channel.DefaultChannelHandlerContext.connect(DefaultChannelHandlerContext.java:479)
	at io.netty.channel.DefaultChannelHandlerContext.connect(DefaultChannelHandlerContext.java:464)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:847)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:198)
	at io.netty.bootstrap.Bootstrap$2.run(Bootstrap.java:187)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:348)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at io.netty.channel.local.LocalChannel$LocalUnsafe.connect(LocalChannel.java:361)
	at io.netty.channel.DefaultChannelPipeline$HeadHandler.connect(DefaultChannelPipeline.java:1008)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1645)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 132782184 bytes (126 MB) / 335544320 bytes (320 MB) up to 5905580032 bytes (5632 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx5612M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	tlauncher_custom_cape_skin{1.0} [TLSkinCape] (tlskincape_1.7.10-1.4.jar) 
	UCHIJAAAA	trainsinmotion{2.4 alpha2021-02-07-16:27} [Trains in Motion] (Traincraft(1).jar) 
	UCHIJAAAA	traincraft{5.0.25.0.1} [Traincraft] (Traincraft(1).jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13596 Compatibility Profile Context 20.10.32 27.20.1032.2' Renderer: 'AMD Radeon(TM) RX Vega 10 Graphics'
	Launched Version: Forge 1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon(TM) RX Vega 10 Graphics GL version 4.6.13596 Compatibility Profile Context 20.10.32 27.20.1032.2, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by EternalBlueFlame** [comment]
Man, I really need to check this branch more.

Yeah this bug was found and fixed for the next build a while ago, thanks for reporting it anyway, never know what may have gone unnoticed.
