### ISSUE TITLE
game crash traincraft 5.0.2

### ISSUE THREAD

**Issue by krakerskrakers** [Mrbrutal/Traincraft-5#108]
The game turns off when the locomotive is turned on, while after inserting a redstone into the locomotive, the locomotive does not respond to power consumption. 

VERSION: TRAINCRAFT 5.0.2

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 30.04.21 22:52
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at ebf.tim.entities.GenericRailTransport.drain(GenericRailTransport.java:1819)
	at ebf.tim.utility.FuelHandler.manageElectricFuel(FuelHandler.java:335)
	at ebf.tim.entities.EntityTrainCore.manageFuel(EntityTrainCore.java:296)
	at ebf.tim.entities.GenericRailTransport.func_70071_h_(GenericRailTransport.java:1081)
	at ebf.tim.entities.EntityTrainCore.func_70071_h_(EntityTrainCore.java:250)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ebf.tim.entities.GenericRailTransport.drain(GenericRailTransport.java:1819)
	at ebf.tim.utility.FuelHandler.manageElectricFuel(FuelHandler.java:335)
	at ebf.tim.entities.EntityTrainCore.manageFuel(EntityTrainCore.java:296)
	at ebf.tim.entities.GenericRailTransport.func_70071_h_(GenericRailTransport.java:1081)
	at ebf.tim.entities.EntityTrainCore.func_70071_h_(EntityTrainCore.java:250)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)

-- Entity being ticked --
Details:
	Entity Type: trainsinmotion.LocoElectricBR_E69.entity (train.entity.trains.EntityLocoElectricBR_E69)
	Entity ID: 380
	Entity Name: BR E69
	Entity's Exact location: -188,50, 64,00, -148,04
	Entity's Block location: World: (-189,64,-149), Chunk: (at 3,4,11 in -12,-10; contains blocks -192,0,-160 to -177,255,-145), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: -0,00, 0,00, 0,00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['pjeter00'/368, l='world', x=-188,50, y=66,82, z=-148,04]]
	Chunk stats: ServerChunkCache: 1089 Drop: 0
	Level seed: 7488547316846263943
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 2;7,59x1,3x3,2;1;
	Level spawn location: World: (-196,4,-140), Chunk: (at 12,0,4 in -13,-9; contains blocks -208,0,-144 to -193,255,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 10884 game time, 6000 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 167671 (now: false), thunder time: 93456 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_291, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 382080600 bytes (364 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	trainsinmotion{2.4 alpha2021-02-07-16:27} [Trains in Motion] (Traincraft.jar) 
	UCHIJAAAA	traincraft{5.0.25.0.1} [Traincraft] (Traincraft.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['pjeter00'/368, l='world', x=-188,50, y=66,82, z=-148,04]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 466.11
	OpenGlRenderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by EternalBlueFlame** [comment]
This is a known issue with the curseforge releases, and has already been fixed in the development builds on my branch of the project.

We're gonna be looking to upstream the changes after we get a few more bugs fixed, there are a LOT of things fixed.
