### ISSUE TITLE
compatibility problem with opencomputers or computercraft mod

### ISSUE THREAD

**Issue by WatoLua** [Mrbrutal/Traincraft-5#122]
This error ends up overloading the server :
`
[Server thread/WARN] [computronics-multiperipheral]: An exception got thrown trying to get a peripheral from provider class train.common.mtc.BlockATOTransmitterStopPoint
java.lang.ClassCastException: cofh.thermalexpansion.block.ender.TileTesseract cannot be cast to dan200.computercraft.api.peripheral.IPeripheral
        at train.common.mtc.BlockATOTransmitterStopPoint.getPeripheral(BlockATOTransmitterStopPoint.java:26) ~[BlockATOTransmitterStopPoint.class:?]
        at pl.asie.computronics.cc.multiperipheral.MultiPeripheralProvider.getAllPeripherals(MultiPeripheralProvider.java:153) [MultiPeripheralProvider.class:?]
        at pl.asie.computronics.cc.multiperipheral.MultiPeripheralProvider.getPeripheral(MultiPeripheralProvider.java:45) [MultiPeripheralProvider.class:?]
        at dan200.computercraft.ComputerCraft.getPeripheralAt(ComputerCraft.java:497) [ComputerCraft.class:?]
        at li.cil.oc.integration.computercraft.DriverPeripheral.findPeripheral(DriverPeripheral.java:59) [DriverPeripheral.class:?]
        at li.cil.oc.integration.computercraft.DriverPeripheral.worksWith(DriverPeripheral.java:80) [DriverPeripheral.class:?]
        at li.cil.oc.server.driver.Registry$$anonfun$2.apply(Registry.scala:118) [Registry$$anonfun$2.class:?]
        at li.cil.oc.server.driver.Registry$$anonfun$2.apply(Registry.scala:118) [Registry$$anonfun$2.class:?]
        at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259) [scala-library-2.11.1.jar:?]
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) [scala-library-2.11.1.jar:?]
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) [scala-library-2.11.1.jar:?]
        at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258) [scala-library-2.11.1.jar:?]
        at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270) [scala-library-2.11.1.jar:?]
        at scala.collection.AbstractTraversable.filter(Traversable.scala:104) [scala-library-2.11.1.jar:?]
        at li.cil.oc.server.driver.Registry$.driverFor(Registry.scala:118) [Registry$.class:?]
        at li.cil.oc.api.Driver.driverFor(Driver.java:174) [Driver.class:?]
        at li.cil.oc.common.tileentity.Adapter.neighborChanged(Adapter.scala:96) [Adapter.class:?]
        at li.cil.oc.common.tileentity.Adapter$$anonfun$neighborChanged$2.apply(Adapter.scala:155) [Adapter$$anonfun$neighborChanged$2.class:?]
        at li.cil.oc.common.tileentity.Adapter$$anonfun$neighborChanged$2.apply(Adapter.scala:154) [Adapter$$anonfun$neighborChanged$2.class:?]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [scala-library-2.11.1.jar:?]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [scala-library-2.11.1.jar:?]
        at li.cil.oc.common.tileentity.Adapter.neighborChanged(Adapter.scala:154) [Adapter.class:?]
        at li.cil.oc.common.tileentity.Adapter.onConnect(Adapter.scala:165) [Adapter.class:?]
        at li.cil.oc.server.network.Node$class.onConnect(Node.scala:57) [Node$class.class:?]
        at li.cil.oc.server.network.Network$NodeBuilder$$anon$4.onConnect(Network.scala:622) [Network$NodeBuilder$$anon$4.class:?]
        at li.cil.oc.server.network.Network$$anonfun$add$9$$anonfun$apply$4.apply(Network.scala:341) [Network$$anonfun$add$9$$anonfun$apply$4.class:?]
        at li.cil.oc.server.network.Network$$anonfun$add$9$$anonfun$apply$4.apply(Network.scala:341) [Network$$anonfun$add$9$$anonfun$apply$4.class:?]
        at scala.collection.immutable.List.foreach(List.scala:383) [scala-library-2.11.1.jar:?]
        at li.cil.oc.server.network.Network$$anonfun$add$9.apply(Network.scala:341) [Network$$anonfun$add$9.class:?]
        at li.cil.oc.server.network.Network$$anonfun$add$9.apply(Network.scala:341) [Network$$anonfun$add$9.class:?]
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778) [scala-library-2.11.1.jar:?]
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) [scala-library-2.11.1.jar:?]
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) [scala-library-2.11.1.jar:?]
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777) [scala-library-2.11.1.jar:?]
        at li.cil.oc.server.network.Network.add(Network.scala:341) [Network.class:?]
        at li.cil.oc.server.network.Network.connect(Network.scala:107) [Network.class:?]
        at li.cil.oc.server.network.Network$Wrapper.connect(Network.scala:772) [Network$Wrapper.class:?]
        at li.cil.oc.server.network.Node$class.connect(Node.scala:44) [Node$class.class:?]
        at li.cil.oc.server.network.Network$ComponentBuilder$$anon$2.connect(Network.scala:634) [Network$ComponentBuilder$$anon$2.class:?]
        at li.cil.oc.server.driver.CompoundBlockEnvironment$$anonfun$onConnect$3.apply(CompoundBlockEnvironment.scala:43) [CompoundBlockEnvironment$$anonfun$onConnect$3.class:?]
        at li.cil.oc.server.driver.CompoundBlockEnvironment$$anonfun$onConnect$3.apply(CompoundBlockEnvironment.scala:42) [CompoundBlockEnvironment$$anonfun$onConnect$3.class:?]
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778) [scala-library-2.11.1.jar:?]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [scala-library-2.11.1.jar:?]
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35) [scala-library-2.11.1.jar:?]
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777) [scala-library-2.11.1.jar:?]
        at li.cil.oc.server.driver.CompoundBlockEnvironment.onConnect(CompoundBlockEnvironment.scala:42) [CompoundBlockEnvironment.class:?]
        at li.cil.oc.server.network.Node$class.onConnect(Node.scala:57) [Node$class.class:?]
        at li.cil.oc.server.network.Network$ComponentBuilder$$anon$2.onConnect(Network.scala:634) [Network$ComponentBuilder$$anon$2.class:?]
        at li.cil.oc.server.network.Network.add(Network.scala:260) [Network.class:?]
        at li.cil.oc.server.network.Network.connect(Network.scala:107) [Network.class:?]
        at li.cil.oc.server.network.Network$Wrapper.connect(Network.scala:772) [Network$Wrapper.class:?]
        at li.cil.oc.server.network.Node$class.connect(Node.scala:44) [Node$class.class:?]
        at li.cil.oc.server.network.Network$NodeBuilder$$anon$4.connect(Network.scala:622) [Network$NodeBuilder$$anon$4.class:?]
        at li.cil.oc.common.tileentity.Adapter.neighborChanged(Adapter.scala:134) [Adapter.class:?]
        at li.cil.oc.common.tileentity.Adapter$$anonfun$neighborChanged$2.apply(Adapter.scala:155) [Adapter$$anonfun$neighborChanged$2.class:?]
        at li.cil.oc.common.tileentity.Adapter$$anonfun$neighborChanged$2.apply(Adapter.scala:154) [Adapter$$anonfun$neighborChanged$2.class:?]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [scala-library-2.11.1.jar:?]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [scala-library-2.11.1.jar:?]
        at li.cil.oc.common.tileentity.Adapter.neighborChanged(Adapter.scala:154) [Adapter.class:?]
        at li.cil.oc.common.tileentity.Adapter.onConnect(Adapter.scala:165) [Adapter.class:?]
        at li.cil.oc.server.network.Node$class.onConnect(Node.scala:57) [Node$class.class:?]
        at li.cil.oc.server.network.Network$NodeBuilder$$anon$4.onConnect(Network.scala:622) [Network$NodeBuilder$$anon$4.class:?]
        at li.cil.oc.server.network.Network.<init>(Network.scala:35) [Network.class:?]
        at li.cil.oc.server.network.Network$.joinNewNetwork(Network.scala:484) [Network$.class:?]
        at li.cil.oc.server.network.Network$$anonfun$joinOrCreateNetwork$1.apply(Network.scala:474) [Network$$anonfun$joinOrCreateNetwork$1.class:?]
        at li.cil.oc.server.network.Network$$anonfun$joinOrCreateNetwork$1.apply(Network.scala:452) [Network$$anonfun$joinOrCreateNetwork$1.class:?]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [scala-library-2.11.1.jar:?]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [scala-library-2.11.1.jar:?]
        at li.cil.oc.server.network.Network$.joinOrCreateNetwork(Network.scala:452) [Network$.class:?]
        at li.cil.oc.api.Network.joinOrCreateNetwork(Network.java:48) [Network.class:?]
        at li.cil.oc.common.EventHandler$$anonfun$scheduleServer$1.apply$mcV$sp(EventHandler.scala:78) [EventHandler$$anonfun$scheduleServer$1.class:?]
        at li.cil.oc.common.EventHandler$$anonfun$onServerTick$1.apply(EventHandler.scala:154) [EventHandler$$anonfun$onServerTick$1.class:?]
        at li.cil.oc.common.EventHandler$$anonfun$onServerTick$1.apply(EventHandler.scala:153) [EventHandler$$anonfun$onServerTick$1.class:?]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [scala-library-2.11.1.jar:?]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186) [scala-library-2.11.1.jar:?]
        at li.cil.oc.common.EventHandler$.onServerTick(EventHandler.scala:153) [EventHandler$.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_960_EventHandler$_onServerTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
`

and this error is printed in a loop in the terminal. But it does not overload the server :

`
[Server thread/WARN] [computronics-multiperipheral]: An exception got thrown trying to get a peripheral from provider class train.common.mtc.BlockATOTransmitterStopPoint
java.lang.ClassCastException: TileMultipart_cmp$$0 cannot be cast to dan200.computercraft.api.peripheral.IPeripheral
        at train.common.mtc.BlockATOTransmitterStopPoint.getPeripheral(BlockATOTransmitterStopPoint.java:26) ~[BlockATOTransmitterStopPoint.class:?]
        at pl.asie.computronics.cc.multiperipheral.MultiPeripheralProvider.getAllPeripherals(MultiPeripheralProvider.java:153) [MultiPeripheralProvider.class:?]
        at pl.asie.computronics.cc.multiperipheral.MultiPeripheralProvider.getPeripheral(MultiPeripheralProvider.java:45) [MultiPeripheralProvider.class:?]
        at dan200.computercraft.ComputerCraft.getPeripheralAt(ComputerCraft.java:497) [ComputerCraft.class:?]
        at dan200.computercraft.shared.util.PeripheralUtil.getPeripheral(PeripheralUtil.java:13) [PeripheralUtil.class:?]
        at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateInput(TileComputerBase.java:331) [TileComputerBase.class:?]
        at dan200.computercraft.shared.computer.blocks.TileComputerBase.onNeighbourChange(TileComputerBase.java:193) [TileComputerBase.class:?]
        at dan200.computercraft.shared.common.BlockGeneric.func_149695_a(BlockGeneric.java:172) [BlockGeneric.class:?]
        at net.minecraft.world.World.func_147460_e(World.java:697) [ahb.class:?]
        at net.minecraft.world.World.func_147459_d(World.java:649) [ahb.class:?]
        at net.minecraft.world.World.func_147444_c(World.java:613) [ahb.class:?]
        at net.minecraft.world.World.markAndNotifyBlock(World.java:488) [ahb.class:?]
        at net.minecraft.world.World.func_147465_d(World.java:466) [ahb.class:?]
        at net.minecraft.world.World.func_147468_f(World.java:573) [ahb.class:?]
        at net.minecraft.block.Block.removedByPlayer(Block.java:1341) [aji.class:?]
        at net.minecraft.block.Block.removedByPlayer(Block.java:1335) [aji.class:?]
        at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:247) [mx.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:296) [mx.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:217) [mx.class:?]
        at cofh.thermalexpansion.block.device.TileActivator.simLeftClick(TileActivator.java:343) [TileActivator.class:?]
        at cofh.thermalexpansion.block.device.TileActivator.func_145845_h(TileActivator.java:158) [TileActivator.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
`

Can you fix it please ?

**Comment by WatoLua** [comment]
`[Server thread/WARN] [computronics-multiperipheral]: An exception got thrown trying to get a peripheral from provider class train.common.mtc.BlockATOTransmitterStopPoint
java.lang.ClassCastException: TileMultipart_cmp$$0 cannot be cast to dan200.computercraft.api.peripheral.IPeripheral
        at train.common.mtc.BlockATOTransmitterStopPoint.getPeripheral(BlockATOTransmitterStopPoint.java:26) ~[BlockATOTransmitterStopPoint.class:?]
        at pl.asie.computronics.cc.multiperipheral.MultiPeripheralProvider.getAllPeripherals(MultiPeripheralProvider.java:153) [MultiPeripheralProvider.class:?]
        at pl.asie.computronics.cc.multiperipheral.MultiPeripheralProvider.getPeripheral(MultiPeripheralProvider.java:45) [MultiPeripheralProvider.class:?]
        at dan200.computercraft.ComputerCraft.getPeripheralAt(ComputerCraft.java:497) [ComputerCraft.class:?]
        at dan200.computercraft.shared.util.PeripheralUtil.getPeripheral(PeripheralUtil.java:13) [PeripheralUtil.class:?]
        at dan200.computercraft.shared.computer.blocks.TileComputerBase.updateInput(TileComputerBase.java:331) [TileComputerBase.class:?]
        at dan200.computercraft.shared.computer.blocks.TileComputerBase.onNeighbourChange(TileComputerBase.java:193) [TileComputerBase.class:?]
        at dan200.computercraft.shared.common.BlockGeneric.func_149695_a(BlockGeneric.java:172) [BlockGeneric.class:?]
        at net.minecraft.world.World.func_147460_e(World.java:697) [ahb.class:?]
        at net.minecraft.world.World.func_147459_d(World.java:649) [ahb.class:?]
        at net.minecraft.world.World.func_147444_c(World.java:613) [ahb.class:?]
        at net.minecraft.world.World.markAndNotifyBlock(World.java:488) [ahb.class:?]
        at net.minecraft.world.World.func_147465_d(World.java:466) [ahb.class:?]
        at powercrystals.minefactoryreloaded.api.ReplacementBlock.replaceBlock(ReplacementBlock.java:30) [ReplacementBlock.class:?]
        at powercrystals.minefactoryreloaded.tile.machine.TileEntityPlanter.activateMachine(TileEntityPlanter.java:83) [TileEntityPlanter.class:?]
        at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryPowered.func_145845_h(TileEntityFactoryPowered.java:103) [TileEntityFactoryPowered.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]`

I also have this error
