### ISSUE TITLE
(1.7.10) Game crashes when removing locomotive

### ISSUE THREAD

**Issue by Alex34fggh** [Mrbrutal/Traincraft-5#78]
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 25/09/19 11:56
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: train/common/mtc/TilePDMInstructionRadio
	at train.common.api.Locomotive.sendMessage(Locomotive.java:1493)
	at train.common.api.Locomotive.disconnectFromServer(Locomotive.java:1524)
	at train.common.api.Locomotive.func_70097_a(Locomotive.java:1226)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: train.common.mtc.TilePDMInstructionRadio
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: dan200/computercraft/api/peripheral/IPeripheral
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 16 more
Caused by: java.lang.ClassNotFoundException: dan200.computercraft.api.peripheral.IPeripheral
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 20 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 290207744 bytes (276 MB) / 788529152 bytes (752 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 13, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	DragonAPI{v22d} [DragonAPI] (DragonAPI+1.7.10+V22d (1).jar) 
	UCHIJAAAA	RotaryCraft{v22d} [RotaryCraft] (RotaryCraft+1.7.10+V22d (2).jar) 
	UCHIJAAAA	tc{4.4.1_020} [Traincraft] (Traincraft-4.4.1_020 (3).jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['CheekiBreeker34'/127, l='New World', x=-149.42, y=74.00, z=-97.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by EternalBlueFlame** [comment]
Wrong git, but yeah this is already fixed for the next release afik.

**Comment by Alex34fggh** [comment]
Do you have the link for the fixed version?

**Comment by EternalBlueFlame** [comment]
It will be released on curseforge whenever our publisher has some time to deal with it.
IIRC there was some extra delays because curse wants some extra paperwork for tax reasons and whatnot, so that's making it take longer too.
